"""Config flow tests for Electricity Planner."""
from __future__ import annotations

import pytest
from homeassistant.data_entry_flow import FlowResultType
from pytest_homeassistant_custom_component.common import MockConfigEntry

from custom_components.electricity_planner.config_flow import OptionsFlowHandler
from custom_components.electricity_planner.const import (
    CONF_BATTERY_CAPACITIES,
    CONF_BATTERY_SOC_ENTITIES,
    CONF_BASE_GRID_SETPOINT,
    CONF_DYNAMIC_THRESHOLD_CONFIDENCE,
    CONF_EMERGENCY_SOC_THRESHOLD,
    CONF_FEEDIN_ADJUSTMENT_MULTIPLIER,
    CONF_FEEDIN_ADJUSTMENT_OFFSET,
    CONF_FEEDIN_PRICE_THRESHOLD,
    CONF_MAX_BATTERY_POWER,
    CONF_MAX_CAR_POWER,
    CONF_MAX_GRID_POWER,
    CONF_MIN_CAR_CHARGING_DURATION,
    CONF_MIN_CAR_CHARGING_THRESHOLD,
    CONF_MIN_SOC_THRESHOLD,
    CONF_PREDICTIVE_CHARGING_MIN_SOC,
    CONF_PRICE_ADJUSTMENT_MULTIPLIER,
    CONF_PRICE_ADJUSTMENT_OFFSET,
    CONF_PRICE_THRESHOLD,
    CONF_SIGNIFICANT_SOLAR_THRESHOLD,
    CONF_SOLAR_PEAK_EMERGENCY_SOC,
    CONF_USE_AVERAGE_THRESHOLD,
    CONF_USE_DYNAMIC_THRESHOLD,
    CONF_VERY_LOW_PRICE_THRESHOLD,
    CONF_MAX_SOC_THRESHOLD,
    DEFAULT_BASE_GRID_SETPOINT,
    DEFAULT_DYNAMIC_THRESHOLD_CONFIDENCE,
    DEFAULT_EMERGENCY_SOC,
    DEFAULT_FEEDIN_ADJUSTMENT_MULTIPLIER,
    DEFAULT_FEEDIN_ADJUSTMENT_OFFSET,
    DEFAULT_FEEDIN_PRICE_THRESHOLD,
    DEFAULT_MAX_BATTERY_POWER,
    DEFAULT_MAX_CAR_POWER,
    DEFAULT_MAX_GRID_POWER,
    DEFAULT_MIN_CAR_CHARGING_DURATION,
    DEFAULT_MIN_CAR_CHARGING_THRESHOLD,
    DEFAULT_MIN_SOC,
    DEFAULT_PREDICTIVE_CHARGING_MIN_SOC,
    DEFAULT_PRICE_ADJUSTMENT_MULTIPLIER,
    DEFAULT_PRICE_ADJUSTMENT_OFFSET,
    DEFAULT_PRICE_THRESHOLD,
    DEFAULT_SIGNIFICANT_SOLAR_THRESHOLD,
    DEFAULT_SOLAR_PEAK_EMERGENCY_SOC,
    DEFAULT_USE_AVERAGE_THRESHOLD,
    DEFAULT_USE_DYNAMIC_THRESHOLD,
    DEFAULT_VERY_LOW_PRICE_THRESHOLD,
    DEFAULT_MAX_SOC,
    DOMAIN,
)


@pytest.mark.asyncio
async def test_options_flow_returns_updated_options():
    entry = MockConfigEntry(domain=DOMAIN, data={})
    handler = OptionsFlowHandler(entry)

    battery_entity = "sensor.main_battery"

    user_input = {
        CONF_MIN_SOC_THRESHOLD: DEFAULT_MIN_SOC,
        CONF_MAX_SOC_THRESHOLD: DEFAULT_MAX_SOC,
        CONF_PRICE_THRESHOLD: 0.123,
        CONF_PRICE_ADJUSTMENT_MULTIPLIER: DEFAULT_PRICE_ADJUSTMENT_MULTIPLIER,
        CONF_PRICE_ADJUSTMENT_OFFSET: DEFAULT_PRICE_ADJUSTMENT_OFFSET,
        CONF_EMERGENCY_SOC_THRESHOLD: DEFAULT_EMERGENCY_SOC,
        CONF_VERY_LOW_PRICE_THRESHOLD: DEFAULT_VERY_LOW_PRICE_THRESHOLD,
        CONF_SIGNIFICANT_SOLAR_THRESHOLD: DEFAULT_SIGNIFICANT_SOLAR_THRESHOLD,
        CONF_FEEDIN_PRICE_THRESHOLD: DEFAULT_FEEDIN_PRICE_THRESHOLD,
        CONF_FEEDIN_ADJUSTMENT_MULTIPLIER: DEFAULT_FEEDIN_ADJUSTMENT_MULTIPLIER,
        CONF_FEEDIN_ADJUSTMENT_OFFSET: DEFAULT_FEEDIN_ADJUSTMENT_OFFSET,
        CONF_USE_DYNAMIC_THRESHOLD: not DEFAULT_USE_DYNAMIC_THRESHOLD,
        CONF_DYNAMIC_THRESHOLD_CONFIDENCE: DEFAULT_DYNAMIC_THRESHOLD_CONFIDENCE,
        CONF_USE_AVERAGE_THRESHOLD: DEFAULT_USE_AVERAGE_THRESHOLD,
        CONF_MIN_CAR_CHARGING_DURATION: DEFAULT_MIN_CAR_CHARGING_DURATION,
        CONF_MAX_BATTERY_POWER: DEFAULT_MAX_BATTERY_POWER,
        CONF_MAX_CAR_POWER: DEFAULT_MAX_CAR_POWER,
        CONF_MAX_GRID_POWER: DEFAULT_MAX_GRID_POWER,
        CONF_MIN_CAR_CHARGING_THRESHOLD: DEFAULT_MIN_CAR_CHARGING_THRESHOLD,
        CONF_SOLAR_PEAK_EMERGENCY_SOC: DEFAULT_SOLAR_PEAK_EMERGENCY_SOC,
        CONF_PREDICTIVE_CHARGING_MIN_SOC: DEFAULT_PREDICTIVE_CHARGING_MIN_SOC,
        CONF_BASE_GRID_SETPOINT: DEFAULT_BASE_GRID_SETPOINT,
        CONF_BATTERY_SOC_ENTITIES: [battery_entity],
        "capacity_sensor_main_battery": 12.5,
    }

    result = await handler.async_step_init(user_input)

    assert result["type"] == FlowResultType.CREATE_ENTRY
    assert result["data"][CONF_PRICE_THRESHOLD] == 0.123
    assert result["data"][CONF_USE_DYNAMIC_THRESHOLD] is (not DEFAULT_USE_DYNAMIC_THRESHOLD)
    assert result["data"][CONF_BATTERY_CAPACITIES] == {battery_entity: 12.5}
    assert "capacity_sensor_main_battery" not in result["data"]
    # Options flow should not have mutated the original entry data
    assert entry.data == {}
