alias: Control Luna Battery Forcible Charge
description: Enable forcible charge at half grid setpoint when > 2000W, otherwise stop
triggers:
  - entity_id: sensor.electricity_planner_grid_setpoint
    trigger: state
  - minutes: /5
    trigger: time_pattern
conditions:
  - condition: not
    conditions:
      - condition: state
        entity_id: sensor.electricity_planner_grid_setpoint
        state: unknown
      - condition: state
        entity_id: sensor.electricity_planner_grid_setpoint
        state: unavailable
actions:
  - choose:
      - conditions:
          - condition: numeric_state
            entity_id: sensor.electricity_planner_grid_setpoint
            above: 2000
        sequence:
          - action: huawei_solar.forcible_charge
            data:
              power: >-
                {{ (
                  (
                    [
                      (states('sensor.electricity_planner_grid_setpoint') | float(0)) -
                      (states('sensor.evcharger_power_2') | float(0)),
                      0
                    ] | max
                  ) / 2
                ) | int }}
              device_id: 5f18f808c2a17aeb3c78b435012f6713
              duration: 15
      - conditions:
          - condition: numeric_state
            entity_id: sensor.electricity_planner_grid_setpoint
            below: 2000
        sequence:
          - action: huawei_solar.stop_forcible_charge
            data:
              device_id: 5f18f808c2a17aeb3c78b435012f6713
mode: restart
